### ISSUE TITLE
关于端口扫描实现方式

### ISSUE THREAD

**Issue by FunnyWolf** [CTF-MissFeng/GoScan#1]
通过readme看到端口扫描用的是nmap的指纹,请问是调用nmap的二进制文件还是,使用golang解析nmap的指纹库呢?这部分代码能否开源呢?

**Comment by CTF-MissFeng** [comment]
> 通过readme看到端口扫描用的是nmap的指纹，请问是调用nmap的二进制文件还是，使用golang解析nmap的指纹库呢？这部分代码能否开源呢？

用goang写的syn方式扫描，指纹为nmap公开的指纹库，在经过优化精简，目前扫描有点问题，正在优化。后期开源项目源码

**Comment by FunnyWolf** [comment]
> > 通过readme看到端口扫描用的是nmap的指纹，请问是调用nmap的二进制文件还是，使用golang解析nmap的指纹库呢？这部分代码能否开源呢？
> 
> 用goang写的syn方式扫描，指纹为nmap公开的指纹库，在经过优化精简，目前扫描有点问题，正在优化。后期开源项目源码

期待~
