### ISSUE TITLE
安装相关问题

### ISSUE THREAD

**Issue by mu0gua** [CTF-MissFeng/GoScan#10]
# 环境安装

1、Postgresql数据库安装
$ apt-get install postgresql postgresql-client # 安装数据库
$ su postgres
$ psql -U postgres     # 默认安装密码为空
$ ALTER USER postgres WITH PASSWORD 'xxxxxx';     # 修改postgre用户数据库密码
$ CREATE DATABASE goscan;     # 创建数据库
$ \q    # 退出

2、sql文件导入，使用数据库管理工具或命令行导入sql文件
***sql里没有插入任何数据，需要执行完sql后手动插入一些数据***
psql -h 127.0.0.1 -U postgres -W -f public.sql

3、Nsq消息队列运行，防火墙开放以下端口
# 0.0.0.0表示监听所有，在外网的要小心
$ nohub ./nsqd -tcp-address 0.0.0.0:4150 -http-address 0.0.0.0:4151 -max-msg-timeout 1h > nsq.log &

# 正式使用 三部曲

# 初始配置
1. 标记config.toml编辑，配置数据库、web、nsq
address改为0.0.0.0可以在外网使用
password同步密码，一定要和clinet配置文件的一样
postgres按照安装的信息填上就行

连上数据库：
psql -U postgres -h 127.0.0.1 -W
***sql里没有添加数据，这个是为了添加账号***
依次执行以下命令
\c goscan
INSERT INTO users(id, username, password, nick_name) values(1, 'root', '$2a$04$4AA4bbrAQfFgjBC31D889.WdfIYkdIC6nRa6UewENsoS.adMv6rr2', 'root');
执行完毕后你将拥有一个账户, 账号 root 密码Admin@&%F^111    *这个密码完全是为了符合后台验证*
更新密码：
UPDATE users SET password='$2a$04$4AA4bbrAQfFgjBC31D889.WdfIYkdIC6nRa6UewENsoS.adMv6rr2';

# 开启web
./Web > web.log &
登陆后，在扫描引擎处配置消息队列，
tcp 地址为： 0.0.0.0:4150
http地址为：0.0.0.0:4151

# 开启扫描agent
配置client下的config.toml
密码一定要和server的一致
然后运行就好了
./client 
或者使用docker编译成images，启动多个实例（Client、config.toml、Dockerfile三个文件单独放一个目录进行编译）
$ docker build -t goscan:v1 .
$ docker run -itd --name scan1 goscan:v1
$ docker run -itd --name scan2 goscan:v1
$ docker run -itd --name scan3 goscan:v1

一点小坑 踩完了
采集速度还可, 再体验体验

密码也可以自己build
附送代码：

```

package main

import (
    "fmt"
	"golang.org/x/crypto/bcrypt"
)

func HashAndSalt(pwd []byte) string {
	hash, err := bcrypt.GenerateFromPassword(pwd, bcrypt.MinCost)
	if err != nil {

	}
	return string(hash)
}
func main(){
    password := "Admin@&%F^111"
    fmt.Print(HashAndSalt([]byte(password)))
}
```

**Comment by CTF-MissFeng** [comment]
![image](https://user-images.githubusercontent.com/38177965/113686883-52cba400-96fa-11eb-8388-1636d829aa10.png)

感谢支持本项目，在boot.go文件里，启动时会自动检测admin账户，不存在则创建哦

**Comment by mu0gua** [comment]
这个隐藏的有点深哟， 可能是我操作的不对，我启动过几次，我看数据库里确实没数据，然后手动插入的，感谢作者回复。

建议可以放一个问题WIKi， 有助于帮助大家答疑。
