### ISSUE TITLE
嗨, 正则匹配无法完全使用

### ISSUE THREAD

**Issue by geeksmy** [CTF-MissFeng/GoScan#12]
https://github.com/CTF-MissFeng/GoScan/blob/96b40f47ed42a9b8b25660e3771bfbaaf34d1fb5/GoScan/Client/plug/portscan/probe/nmap.go#L201
使用regexp 这个库,无法完全使用 nmap-service-probes指纹库里的正则. 建议使用go-pcre, 但是此库只支持 linux 和 mac. 未针对 windows 做适配.  https://github.com/geeksmy/go-pcre.git 这个对windows, linux, mac 做了兼容.

**Comment by CTF-MissFeng** [comment]
感谢建议，最终目的是能快读识别常见可利用漏洞服务，所以精简了很多nmap服务规则，所以没必要将nmap全部规则都匹配一次
