### ISSUE TITLE
static.go源文件

### ISSUE THREAD

**Issue by taoharry** [CTF-MissFeng/GoScan#16]
作者您好: 我对您在代码中写的static.go中data比较感兴趣, 不知道您可以提供下data数据吗?

**Comment by CTF-MissFeng** [comment]
static.go就是nmap-service-probes文件，因为那时golang还没出go:embed功能，所以只有先把文件转成go了

**Comment by taoharry** [comment]
这个文件链接找到了https://nmap.org/book/vscan-fileformat.html, 感谢大佬指点, 也感谢写出这么实用的项目.
