### ISSUE TITLE
升级问题

### ISSUE THREAD

**Issue by Lekou520** [CTF-MissFeng/GoScan#3]
V0.01版本如何升级到0.2，或0.2是否有部署文档。

**Comment by CTF-MissFeng** [comment]
0.2压缩包中没有nsq，需要单独下载，获取下载0.1中有。部署参考0.1的部署：https://github.com/CTF-MissFeng/GoScan/tree/1f51fd92805fa4468333b117a44610ed53edd4ba

**Comment by Lekou520** [comment]
你好，在0.2安装过程中遇到一个问题
客户端节点启动时报错，在客户端服务器上使用nc链接两个nsp端口均正常访问。
![image](https://user-images.githubusercontent.com/76936213/106692817-2ae39580-6610-11eb-98be-c8dab83e31a7.png)

**Comment by CTF-MissFeng** [comment]
nsq需要开启两个，例如 4150和4151端口，然后在web页面扫描引擎中设置对应的ip:port，你这里4150未开启

**Comment by CTF-MissFeng** [comment]
我这里写一篇部署教程吧，请参考

**Comment by Lekou520** [comment]
好的，谢谢你。这边测试确实是端口通的。
![image](https://user-images.githubusercontent.com/76936213/106709548-ac96eb80-662f-11eb-8154-b52c0f122874.png)

**Comment by CTF-MissFeng** [comment]
![image](https://user-images.githubusercontent.com/38177965/106710657-43b07300-6631-11eb-85dd-87ec35744a33.png)

哦，你这里是扫描引擎中子域名nsq超时过大，请在web页面中修改超时，或者启动nsq时配置最大超时

**Comment by CTF-MissFeng** [comment]
$ nohup ./client/nsqd -tcp-address 本机IP:4151 -http-address 127.0.0.1:10002 --data-path=./client > client.log 2>&1 &

$ nohup ./server/nsqd -max-msg-timeout 1h -tcp-address 本机ip:4150 -http-address 127.0.0.1:10001 --data-path=./server > server.log 2>&1 &

**Comment by Lekou520** [comment]
已解决，非常感谢。
