### ISSUE TITLE
综合扫描功能，无端口及web识别信息，仅有子域名

### ISSUE THREAD

**Issue by lif3reb00t** [CTF-MissFeng/GoScan#4]
在18号添加扫描的，但是没有端口、web相关信息
![image](https://user-images.githubusercontent.com/37888957/108943315-86df8e00-7693-11eb-8ada-79d378bcad87.png)

18号的web探测提示   连接任务队列服务器成功
![image](https://user-images.githubusercontent.com/37888957/108943423-bdb5a400-7693-11eb-9486-5f75b1c04b39.png)

19号的端口扫描日志都是无效端口号报错
![image](https://user-images.githubusercontent.com/37888957/108943358-9d85e500-7693-11eb-993c-b90aac2121c0.png)

**Comment by CTF-MissFeng** [comment]
扫描引擎 端口参数设置错误

**Comment by K3vinPlus** [comment]
好的，谢谢。我再看看
