### ISSUE TITLE
总是账号或密码不正确

### ISSUE THREAD

**Issue by Mitnick0x** [CTF-MissFeng/GoScan#8]
![image](https://user-images.githubusercontent.com/62422553/110676920-7e4c9300-820f-11eb-9f81-64a8313e4a4b.png)

**Comment by xiahao90** [comment]
希望作者来解决一下哦， 我也想观摩一下

**Comment by aiwennba** [comment]
是的，一直账号密码不对

**Comment by madneal** [comment]
同求，demo账号好像改掉了

**Comment by rgzn-aiyun** [comment]
id:admin

**Comment by CTF-MissFeng** [comment]
测试环境已下线，请自己搭建测试，感谢！

**Comment by rgzn-aiyun** [comment]
> 测试环境已下线，请自己建造测试，感谢！

Hi, is this project still being updated?
